initScope: npmScopes

nodeLinker: node-modules

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmAuthToken: DBB3DC19-9679-4EBE-B370-1A89E00CE47E
    npmRegistryServer: 'https://npm.fontawesome.com'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.6.3.cjs
