name: Deploy Development Enviroment

on:
  workflow_dispatch:

env:
  DEPLOY_URL: ${{ vars.DEPLOY_URL_DEV }}
  DEPLOY_PATH: ${{ vars.DEPLOY_PATH_DEV }}
  ASTRO_DISABLE_INDEXING: ${{ vars.ASTRO_DISABLE_INDEXING }}
  ASTRO_GTAG_ID: ${{ vars.ASTRO_GTAG_ID_DEV }}
  ASTRO_GTM_ID: ${{ vars.ASTRO_GTM_ID_DEV }}
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
  FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
  SANITY_STUDIO_PROJECT_ID: ${{ secrets.SANITY_STUDIO_PROJECT_ID }}
  SANITY_STUDIO_DATASET: ${{ secrets.SANITY_STUDIO_DATASET_DEV }}
  DEPLOY_SSH_HOST: ${{ secrets.DEPLOY_SSH_HOST }}
  DEPLOY_SSH_USERNAME: ${{ secrets.DEPLOY_SSH_USERNAME }}
  DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
  DEPLOY_SSH_PASSPHRASE: ${{ secrets.DEPLOY_SSH_PASSPHRASE }}
  DEPLOY_SSH_PORT: ${{ secrets.DEPLOY_SSH_PORT }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    outputs:
      slack-message-id: ${{ steps.slack-initial.outputs.ts }}

    steps:
      - name: 🔀 Checkout
        uses: actions/checkout@v4.1.1

      - name: 💬 Initial Slack Message
        id: slack-initial
        uses: weareliondev/weareliondev-devops/.github/actions/slack/notifications/deploy/initial@main
        with:
          slack-bot-token: ${{ env.SLACK_BOT_TOKEN }}
          slack-channel-id: ${{ env.SLACK_CHANNEL_ID }}
          deploy-url: ${{ env.DEPLOY_URL }}
          context-status: 'Running: Test'

      - uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'

      - name: 🐱‍🏍 Install Yarn
        uses: weareliondev/weareliondev-devops/.github/actions/yarn/install@main
        with:
          cwd: '.'
          enable-corepack: false
          cache-node-modules: true
          cache-install-state: true
          fontawesome: true
          fontawesome-npm-token: ${{ env.FONTAWESOME_NPM_AUTH_TOKEN }}

      - name: 🦋 Prettier Check
        shell: bash
        run: |
          yarn format:ci

      - name: 📚 ESLint Check
        shell: bash
        run: |
          yarn lint

      - name: 💬 Update Slack Message
        uses: weareliondev/weareliondev-devops/.github/actions/slack/notifications/deploy/update@main
        with:
          initial-message: ${{ steps.slack-initial.outputs.ts }}
          slack-bot-token: ${{ env.SLACK_BOT_TOKEN }}
          slack-channel-id: ${{ env.SLACK_CHANNEL_ID }}
          deploy-url: ${{ env.DEPLOY_URL }}
          context-status: 'Preparing: Build Astro'

      - name: 💬 Failure Slack Message
        if: failure()
        uses: weareliondev/weareliondev-devops/.github/actions/slack/notifications/deploy/failed@main
        with:
          initial-message: ${{ steps.slack-initial.outputs.ts }}
          slack-bot-token: ${{ env.SLACK_BOT_TOKEN }}
          slack-channel-id: ${{ env.SLACK_CHANNEL_ID }}
          deploy-url: ${{ env.DEPLOY_URL }}
          context-status: 'Failed: Test'

  build:
    name: Build Astro
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: 🔀 Checkout
        uses: actions/checkout@v4.1.1

      - name: 💬 Update Slack Message
        uses: weareliondev/weareliondev-devops/.github/actions/slack/notifications/deploy/update@main
        with:
          initial-message: ${{ needs.test.outputs.slack-message-id }}
          slack-bot-token: ${{ env.SLACK_BOT_TOKEN }}
          slack-channel-id: ${{ env.SLACK_CHANNEL_ID }}
          deploy-url: ${{ env.DEPLOY_URL }}
          context-status: 'Running: Build Astro'

      - uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'

      - name: Install Yarn
        uses: weareliondev/weareliondev-devops/.github/actions/yarn/install@main
        with:
          cwd: '.'
          enable-corepack: false
          cache-node-modules: true
          cache-install-state: true
          fontawesome: true
          fontawesome-npm-token: ${{ env.FONTAWESOME_NPM_AUTH_TOKEN }}
          
      - name: 🗃️ Create .env file for frontend
        uses: SpicyPizza/create-envfile@v2.0.2
        with:
          envkey_SANITY_STUDIO_PROJECT_ID: ${{ env.SANITY_STUDIO_PROJECT_ID }}
          envkey_SANITY_STUDIO_DATASET: ${{ env.SANITY_STUDIO_DATASET }}
          envkey_ASTRO_WEBSITE_URL: ${{ env.DEPLOY_URL }}
          envkey_ASTRO_DISABLE_INDEXING: ${{ env.ASTRO_DISABLE_INDEXING }}
          envkey_ASTRO_GTAG_ID: ${{ env.ASTRO_GTAG_ID }}
          envkey_ASTRO_GTM_ID: ${{ env.ASTRO_GTM_ID }}
          file_name: .env

      - name: 🗳️ Run Env Variables Check
        shell: bash
        run: |
          yarn env:check

      - name: ⚙️ Build
        shell: bash
        run: |
          yarn build

      - name: ⚙️ Copy .htaccess file
        shell: bash
        run: |
          mv deployment/apache/.htaccess .htaccess

      - name: 📥 Tar Build
        shell: bash
        run: |
          tar -cvzf dist.tar.gz dist .env .htaccess

      - name: 📦 Store Build
        uses: actions/upload-artifact@v3.1.3
        with:
          name: dev-deployment-build
          path: dist.tar.gz
          retention-days: 1

      - name: 💬 Update Slack Message
        uses: weareliondev/weareliondev-devops/.github/actions/slack/notifications/deploy/update@main
        with:
          initial-message: ${{ needs.test.outputs.slack-message-id }}
          slack-bot-token: ${{ env.SLACK_BOT_TOKEN }}
          slack-channel-id: ${{ env.SLACK_CHANNEL_ID }}
          deploy-url: ${{ env.DEPLOY_URL }}
          context-status: 'Preparing: Deploy To Hosting'

      - name: 💬 Failure Slack Message
        if: failure()
        uses: weareliondev/weareliondev-devops/.github/actions/slack/notifications/deploy/failed@main
        with:
          initial-message: ${{ needs.test.outputs.slack-message-id }}
          slack-bot-token: ${{ env.SLACK_BOT_TOKEN }}
          slack-channel-id: ${{ env.SLACK_CHANNEL_ID }}
          deploy-url: ${{ env.DEPLOY_URL }}
          context-status: 'Failed: Build Astro'

  deploy:
    name: Deploy to hosting
    runs-on: ubuntu-latest
    needs: [test, build]
    steps:
      - name: 🔀 Checkout
        uses: actions/checkout@v3

      - name: ♻️ Restore Build from previous job
        uses: actions/download-artifact@v3.0.2
        with:
          name: dev-deployment-build
          path: dist.tar.gz

      - name: 📤 Untar Build
        shell: bash
        run: |
          tar -xvzf dist.tar.gz/dist.tar.gz -C ./
          rm -rf dist.tar.gz

      - name: 📀 Deploy to LionDev Cloud
        id: deploy-to-plesk
        uses: weareliondev/weareliondev-devops/.github/actions/deploy/astro@main
        with:
          host: ${{ env.DEPLOY_SSH_HOST }}
          username: ${{ env.DEPLOY_SSH_USERNAME }}
          key: ${{ env.DEPLOY_SSH_KEY }}
          passphrase: ${{ env.DEPLOY_SSH_PASSPHRASE }}
          port: ${{ env.DEPLOY_SSH_PORT }}
          source: 'dist/**,.env,.htaccess'
          deploy-path: ${{ env.DEPLOY_PATH }}

      - name: 💬 Update Slack Message
        uses: weareliondev/weareliondev-devops/.github/actions/slack/notifications/deploy/success@main
        with:
          initial-message: ${{ needs.test.outputs.slack-message-id }}
          slack-bot-token: ${{ env.SLACK_BOT_TOKEN }}
          slack-channel-id: ${{ env.SLACK_CHANNEL_ID }}
          deploy-url: ${{ env.DEPLOY_URL }}
          context-status: 'Success: Deploy to hosting'

      - name: 💬 Failure Slack Message
        if: failure()
        uses: weareliondev/weareliondev-devops/.github/actions/slack/notifications/deploy/failed@main
        with:
          initial-message: ${{ needs.test.outputs.slack-message-id }}
          slack-bot-token: ${{ env.SLACK_BOT_TOKEN }}
          slack-channel-id: ${{ env.SLACK_CHANNEL_ID }}
          deploy-url: ${{ env.DEPLOY_URL }}
          context-status: 'Failed: Deploy to hosting'
